{"name": "test_pipeline_failure_recovery", "status": "passed", "description": "Test pipeline failure and recovery scenarios.", "start": 1751312139022, "stop": 1751312139022, "uuid": "6975a9ef-d972-4473-ac31-5b1cc0612b2d", "historyId": "776190be56d58c56f5feed06274b936b", "testCaseId": "776190be56d58c56f5feed06274b936b", "fullName": "end_to_end.test_video_pipeline_e2e.TestVideoPipelineE2E#test_pipeline_failure_recovery", "labels": [{"name": "tag", "value": "bug_discovery"}, {"name": "tag", "value": "pyramid_functional"}, {"name": "tag", "value": "functional"}, {"name": "parentSuite", "value": "end_to_end"}, {"name": "suite", "value": "test_video_pipeline_e2e"}, {"name": "subSuite", "value": "TestVideoPipelineE2E"}, {"name": "host", "value": "fealfr"}, {"name": "thread", "value": "30472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "end_to_end.test_video_pipeline_e2e"}]}